name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        nver: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nver }}
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build